image: lovullo/php-ci

include:
    - project: 'devops/shared-pipelines'
      file: '/jobs-common.yml'
    - project: 'devops/shared-pipelines'
      file: '/jobs-composer-install.yml'
    - project: 'devops/shared-pipelines'
      file: '/jobs-php-static-analysis.yml'

variables:
    # Ignores/excludes for static analysis checks
    phpcs_ignore: 'app/,bin/,vendor/,test/,web/,var'
    phpmd_ignore: 'app,bin,vendor,test,web,var'
    phpcpd_ignore: '--exclude vendor
                    --exclude app
                    --exclude web
                    --exclude tests
                    --exclude bin
                    --exclude var'
    phpcs_standard: 'PSR12'

stages:
    - build
    - test
    - deploy
    - post-deploy

before_script:
    # Start ssh-agent, so we can clone dependencies
    - eval $(ssh-agent -s)

    # Add the SSH key which has access to clone dependencies
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

